language: ruby
rvm:
 - 2.4.1
services:
- postgresql
install:
- gem install rails
- bundle install
script:
- bundle exec rake db:{create,migrate,seed}
notifications:
  email: false
deploy:
  provider: heroku
  api_key: false
