language: ruby
rvm:
 - 2.4.1
services:
- postgresql
install: gem install rails
before_script:
- bundle install
- rake db:{create,migrate,seed}
notifications:
  email: false
deploy:
  provider: heroku
  
